<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateApiClient>false</GenerateApiClient>
  </PropertyGroup>

  <Import Project="../Packable.Projects.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.3" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.15.0" />
    <PackageReference Include="Polly.Contrib.WaitAndRetry" Version="1.1.1" />
    <PackageReference Include="NSwag.MSBuild" Version="14.6.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Polly.Extensions.Http" Version="3.0.0" />
    <PackageReference Include="Polly.Caching.Memory" Version="3.0.2" />
    <PackageReference Include="Trakx.Common.ApiClient" Version="2.1.2" />
    <PackageReference Include="Trakx.Common.Configuration" Version="2.1.2" />
  </ItemGroup>

  <Target Name="NSwag" BeforeTargets="Build" Condition="'$(GenerateApiClient)'=='True' ">
    <Copy SourceFiles="@(Reference)" DestinationFolder="$(OutDir)References" />
    <Exec Command="$(NSwagExe_Net100) run nswag.json /variables:Configuration=$(Configuration)" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>

</Project>
