name: Build and Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev, stage, prod ]
  workflow_call:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test and cover solutions
        id: test
        uses: trakx/github-actions/test-dotnet@v10.0.22
        with:
          packageReadonlyPat: ${{secrets.TRAKX_BOT_READONLY_PAT}}
          codacyToken: ${{secrets.CODACY_TOKEN}}
          awsAccessKeyId: ${{secrets.AWS_ACCESS_KEY_ID}}
          awsAccessKeySecret: ${{secrets.AWS_ACCESS_KEY_SECRET}}
